apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
      version: "2"
  template:
    metadata:
      labels:
        app: nginx-server
        version: "2"
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.4-alpine
          ports:
            - containerPort: 80
